# Medrano Hernández Vanesa Mnserrat
name: Hello World with WorkFlow
on: 
  workflow_dispatch:

jobs:
  # Mi job 1
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"

      - name: Fecha hoy
        run: date
